"""add is_deleted flag

Revision ID: e10268171233
Revises: 423d3a89ddda
Create Date: 2025-12-23 22:00:41.875795

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e10268171233"
down_revision: Union[str, Sequence[str], None] = "423d3a89ddda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("is_deleted", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "is_deleted")
    # ### end Alembic commands ###
